### ISSUE TITLE
[golang] auditv1.AuditLogWrittenEvent{} unable to unmarshall CloudRun AuditLog Event

### ISSUE THREAD

**Issue by salrashid123** [googleapis/google-cloudevents-go#11]
AuditLogs for events for Cloud Run cannot be unmarshalled using the cloud-events SDK's [event.DataAs{}](https://godoc.org/github.com/cloudevents/sdk-go/v2/event#Event.DataAs)   with a struct of type `auditv1.AuditLogWrittenEvent{}` 

For example, the if the snippet below is received either as a pubsub or run event as a GCP AuditLog, the code throws a parsing error as shown below

```golang
		audit_data := &auditv1.AuditLogWrittenEvent{}
		if err := event.DataAs(audit_data); err != nil {
			fmt.Printf("DataAs Error %v", err)
			return fmt.Errorf("Got Data Error: %s\n", err)
		}
		fmt.Printf("Audit ResourceName %s\n", audit_data.ProtoPayload)
```

```
2020/09/23 18:12:28 projects/mineral-minutia-820/logs/cloudaudit.googleapis.com%2Factivityyopiilehxskr1600899141625294
DataAs Error [json] found bytes "{"protoPayload":{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":...
, but failed to unmarshal: json: cannot unmarshal string into Go struct field AuditLogWrittenEvent.severity of type int64
```

i suspect there is a core mismatch either on the event from GCP or the source proto thats used to generate the AuditLogWirttenEvent.

---

What i can state is the following work to unmarshall the LogEntry first as DataAs and then as an AuditLog messagge

```golang
import (
      	logging "google.golang.org/api/logging/v2"
	svc "google.golang.org/api/servicecontrol/v1"
)
		loggingData := &logging.LogEntry{}
		if err := event.DataAs(loggingData); err != nil {
			return fmt.Errorf("Got Data Error %v", err)
		}
		audit_data := &svc.AuditLog{}

		err := json.Unmarshal(loggingData.ProtoPayload, audit_data)
		if err != nil {
			return fmt.Errorf("Got Data Error %v", err)
		}
		fmt.Printf("Audit ResourceName %s\n", audit_data.ResourceName)
```

pls comare the combined logging.LogEntry{} with svc.AuditLog{} struct as provided by `google.golang.org/api/servicecontrol/v1`  and the logging library agasint `auditv1.AuditLogWrittenEvent{}`.  You can verify/repo this by subcribing to a cloud run audit event.

**Comment by grant** [comment]
I think this issue was due to a bug in CAL payloads not being correct. This should be fixed now.

**Comment by salrashid123** [comment]
thanks, confirmed it works now
