### ISSUE TITLE
json: invalid use of ,string struct tag, trying to unmarshal unquoted value into *int64

### ISSUE THREAD

**Issue by erikbohnsack** [googleapis/google-cloudevents-go#125]
Hello! 

We're using Pub/Sub notifications for Google Cloud Storage, which upon receival we `json.Unmarshal` to `storage.StorageObjectData`. When enabling parallel composite uploads using `gsutil` we stumble upon an error. 

```go
        [...]
	var e storage.StorageObjectData
        err := json.Unmarshal(msg.Data, &e)
```
will return: `json: invalid use of ,string struct tag, trying to unmarshal unquoted value into *int64` as the `componentCount` field in the payload is `"componentCount": 10` (or some other integer). 

Disclaimer: I saw the comment regarding that this is under heavy refactoring, but thought I would lift this to the surface. 

#### Environment details

  - Programming language: Go
  - OS: Cloud Run instance running a simple go-binary based on `gcr.io/distroless/static:nonroot` 
  - Language runtime version: 1.17
  - Package version: `v2.3.0` 

#### Steps to reproduce

```go 
package unmarshal_test

import (
	"encoding/json"
	"testing"
        
        "github.com/googleapis/google-cloudevents-go/cloud/storage/v1"
)

func TestUnmarshalComponentCount(t *testing.T) {
	data := `{"componentCount": 16}` 
	var e storage.StorageObjectData
	if err := json.Unmarshal([]byte(data), &e); err != nil {
		t.Errorf("failed: %v", err)
	}
}
```

Copying the struct definition locally and removing `string` in the `ComponentCount` json field tag does not have this problem.

**Comment by pattishin** [comment]
Hi Erik, 
Thanks for your patience and taking time to document this issue! As this is still under heavy maintenance, will be closing this out for now. Once we've completed the refactoring and if this is still an issue, do please raise this up again!
