### ISSUE TITLE
cannot unmarshal string into Go struct field StorageObjectData.generation of type int64

### ISSUE THREAD

**Issue by namnhatdoan** [googleapis/google-cloudevents-go#178]
I'm writing a gcloud function that handle new file uploaded into storage bucket and it's failed to unmarshall event data into StorageObjectData.

#### Environment details

  - Programming language: Golang
  - OS: 
  - Language runtime version: Go 1.19
  - Package version: v0.6.0

#### Steps to reproduce

My function is simple:
```
package functions

import (
	"context"

	_ "github.com/GoogleCloudPlatform/functions-framework-go/funcframework"
	"github.com/googleapis/google-cloudevents-go/cloud/storagedata"
	"github.com/sirupsen/logrus"
)

func StorageWrite(ctx context.Context, data *storagedata.StorageObjectData) error {
	log := logrus.WithContext(ctx).WithField("name", data.Name).WithField("data", data)
	log.Info("Executed")
	return nil
}
```

I deployed with this trigger-event "providers/cloud.storage/eventTypes/object.change" 

Error logs:

> image_writezdfhzqyqwy14 Error: json: cannot unmarshal string into Go struct field StorageObjectData.generation of type int64, while converting event data: {"bucket":"anhemdev-dummy","contentType":"image/png","crc32c":"RDX58Q==","etag":"CMmpzM/W5f8CEAE=","generation":"1687945399702729","id":"anhemdev-dummy/tokens.png/1687945399702729","kind":"storage#object","md5Hash":"Y2JkMGQxNDExOTRiYTY1NWQzYmUwNzA5YTJhZWViYzY=","mediaLink":"https://storage.googleapis.com/download/storage/v1/b/anhemdev-dummy/o/tokens.png?generation=1687945399702729&alt=media","metageneration":"1","name":"tokens.png","resourceState":"exists","selfLink":"https://www.googleapis.com/storage/v1/b/anhemdev-dummy/o/tokens.png","size":"217170","storageClass":"STANDARD","timeCreated":"2023-06-28T09:43:19.717Z","timeStorageClassUpdated":"2023-06-28T09:43:19.717Z","updated":"2023-06-28T09:43:19.717Z"}

Thank you

**Comment by averikitsch** [comment]
Hi @namnhatdoan, I don't believe you can use this library with Cloud functions 1st gen. Go experts @grayside and @muncus may have a work around for this use case. I recommend looking at sample and tutorial, https://cloud.google.com/functions/docs/tutorials/storage, that use Cloud Functions 2nd gen to parse StorageObjectData from a CloudEvent.

**Comment by grayside** [comment]
Thank you @namnhatdoan for opening this issue with detailed logs.

As @averikitsch said. You will note the linked tutorial uses `--trigger-event-filters="type=google.cloud.storage.object.v1.finalized"` and also shows how CloudEvent functions are given an Event object, which is then used to explicitly unmarshal data using this library inside the function implementation.

For a broader introduction to CloudEvent functions, see https://cloud.google.com/functions/docs/writing/write-event-driven-functions

Please reopen this issue if there is a further concern about library behavior.

**Comment by namnhatdoan** [comment]
Hi, Thank you for your reply and sorry for my late response. This is just an update from my side and share my work around if some one want to do the same thing.

My team decided to not upgrade to 2nd gen gcloud functions for now so we continued to do it with 1st gen. I worked around for this case by creating another struct that inherit from this and modify it a little bit
- For int fields, add "string" into json annotation.
- For timestamp fields, using time.Time instead.

Something like this
`type StorageObjectData struct {
	*storagedata.StorageObjectData
	Name string `protobuf:"bytes,23,opt,name=name,proto3" json:"name,omitempty"`
	Id   string `protobuf:"bytes,24,opt,name=id,proto3" json:"id,omitempty"`

	Generation     int64 `protobuf:"varint,26,opt,name=generation,proto3" json:"generation,string,omitempty"`
	Metageneration int64 `protobuf:"varint,6,opt,name=metageneration,proto3" json:"metageneration,string,omitempty"`
	Size           int64 `protobuf:"varint,9,opt,name=size,proto3" json:"size,string,omitempty"`
	ComponentCount int32 `protobuf:"varint,12,opt,name=component_count,json=componentCount,proto3" json:"component_count,string,omitempty"`

	TimeCreated             time.Time `protobuf:"bytes,10,opt,name=time_created,json=timeCreated,proto3" json:"time_created,omitempty"`
	TimeDeleted             time.Time `protobuf:"bytes,7,opt,name=time_deleted,json=timeDeleted,proto3" json:"time_deleted,omitempty"`
	Updated                 time.Time `protobuf:"bytes,15,opt,name=updated,proto3" json:"updated,omitempty"`
	TimeStorageClassUpdated time.Time `protobuf:"bytes,18,opt,name=time_storage_class_updated,json=timeStorageClassUpdated,proto3" json:"time_storage_class_updated,omitempty"`
	RetentionExpirationTime time.Time `protobuf:"bytes,20,opt,name=retention_expiration_time,json=retentionExpirationTime,proto3" json:"retention_expiration_time,omitempty"`
}`

For my real use case, I actually just declare some fields that need to be handled instead of support all fields like this.

Thanks
