### ISSUE TITLE
Add json hints for unmarshal types like int64

### ISSUE THREAD

**Issue by markxp** [googleapis/google-cloudevents-go#184]
I transported Cloud Stroage object.finalize events through Pub/Sub. When I decoded the event from pubsub message body, it failed with error message like this: `json: cannot unmarshal string into Go struct field StorageObjectData.generation of type int64 `

I temporary solved this issue by [adding `json: ",string"` tags](https://stackoverflow.com/questions/21151765/cannot-unmarshal-string-into-go-value-of-type-int64). Could it be possible to add the tags? It can help json unmarshal successfully.

**Comment by grayside** [comment]
Hello @markxp, thanks for opening an issue.

The Event Types in this library are specific to CloudEvent packaged data (e.g., delivered by Eventarc). Delivering a Cloud Storage notification via Pub/Sub is a complete valid way to handle storage events, but it's not quiet the same event API contract as this library supports, as you can see from this int64 error.

The type you are hoping to use is compatible with one of these event types: https://cloud.google.com/eventarc/docs/event-types#cloud-storage

This library is generated from proto definitions of the event types so customizations of struct tags are not supported.
