### ISSUE TITLE
Cannot parse LogEntryData (google.cloud.audit.log.v1.written type) with latest google-cloudevents-go

### ISSUE THREAD

**Issue by salrashid123** [googleapis/google-cloudevents-go#22]
Latest commit to `github.com/googleapis/google-cloudevents-go` seems to break parsing GCP audit log types

In the following snippet, if i use  `github.com/googleapis/google-cloudevents-go v0.0.0-20201014214533-8f932ccdc752`, i can use the cloud-events go SDK `event.DataAs()` fine but if i upgrade to `github.com/googleapis/google-cloudevents-go v0.0.0-20201106055002-2d7dd1dcf649 `, i'll see the error shown below about `LogEntryData.severity ` 

---

```
require (
	cloud.google.com/go v0.71.0 // indirect
	github.com/cloudevents/sdk-go/protocol/pubsub/v2 v2.3.1
	github.com/cloudevents/sdk-go/v2 v2.3.1
	github.com/googleapis/google-cloudevents-go v0.0.0-20201014214533-8f932ccdc752  // works
	github.com/googleapis/google-cloudevents-go v0.0.0-20201106055002-2d7dd1dcf649  // does not work
	google.golang.org/api v0.35.0
)
```

```golang
import  (
	auditv1 "github.com/googleapis/google-cloudevents-go/cloud/audit/v1"
)
		auditData := &auditv1.LogEntryData{}
		if err := event.DataAs(auditData); err != nil {
			fmt.Printf("DataAs Error %v", err)
			return fmt.Errorf("Got Data Error: %s\n", err)
		}
		log.Printf("Audit v ResourceName %s\n", *auditData.ProtoPayload.ResourceName)
```

gives

```log
DataAs Error [json] found bytes "", 
but failed to unmarshal: json: 
   cannot unmarshal string into Go struct field LogEntryData.severity of type audit.NumResponseItems
```

**Comment by grant** [comment]
Something is incorrect with the JSON schema generator for Go.

https://github.com/googleapis/google-cloudevents-go/blob/master/cloud/audit/v1/log_entry_data.go

It's producing a field called `NumResponseItems` in multiple places where it's not correct.

https://github.com/googleapis/google-cloudevents-go/blob/c18c6a1c1f1fa38f650ed0bf133563989827a18f/cloud/audit/v1/log_entry_data.go#L355

Will have to file a bug in QuickType and find the upstream issue (related to enum types).

**Comment by grant** [comment]
The latest commit should have a fix for this issue @salrashid123.
