### ISSUE TITLE
Error when parsing google.cloud.storage.object.v1.finalized events using storage.UnmarshalStorageObjectData

### ISSUE THREAD

**Issue by eclipselu** [googleapis/google-cloudevents-go#39]
## Expected Behavior

We're able to parse the event and populate data into StorageObjectData object.

## Actual Behavior

Got the following error instead: 

```
{"level":"error","ts":1610564646.3508415,"logger":"fallback","caller":"client/invoker.go:66","msg":"call to Invoker.Invoke(...) has panicked: json: cannot unmarshal string into Go struct field StorageObjectData.generation of type int64","stacktrace":"..."}
```

pretty printed stacktrace: 
```go
github.com/cloudevents/sdk-go/v2/client.(*receiveInvoker).Invoke.func2.1
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.3.1/client/invoker.go:66
runtime.gopanic
        /usr/local/go/src/runtime/panic.go:969
main.Receive
        /app/main.go:35
reflect.Value.call
        /usr/local/go/src/reflect/value.go:476
reflect.Value.Call
        /usr/local/go/src/reflect/value.go:337
github.com/cloudevents/sdk-go/v2/client.(*receiverFn).invoke
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.3.1/client/receiver.go:86
github.com/cloudevents/sdk-go/v2/client.(*receiveInvoker).Invoke.func2
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.3.1/client/invoker.go:69
github.com/cloudevents/sdk-go/v2/client.(*receiveInvoker).Invoke
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.3.1/client/invoker.go:71
github.com/cloudevents/sdk-go/v2/client.(*ceClient).StartReceiver.func2.1
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.3.1/client/client.go:233
```

### Event (in go object format)

```Validation: valid
Context Attributes,
  specversion: 1.0
  type: google.cloud.storage.object.v1.finalized
  source: //storage.googleapis.com/projects/_/buckets/events-quickstart-danglu-knative-dev-290519
  subject: objects/go-test-123.txt
  id: 1911674720947509
  time: 2021-01-13T19:03:20.8Z
  dataschema: https://raw.githubusercontent.com/googleapis/google-cloudevents/master/proto/google/events/cloud/storage/v1/data.proto
  datacontenttype: application/json
Extensions,
  knativearrivaltime: 2021-01-13T19:03:21.568106765Z
  knsourcetrigger: link0.8966907269185795
  traceparent: 00-31c5577593932217af33e2c0ab5dcf12-32037e59dd69f8b4-00
Data,
  {
    "kind": "storage#object",
    "id": "events-quickstart-danglu-knative-dev-290519/go-test-123.txt/1610564600595212",
    "selfLink": "https://www.googleapis.com/storage/v1/b/events-quickstart-danglu-knative-dev-290519/o/go-test-123.txt",
    "name": "go-test-123.txt",
    "bucket": "events-quickstart-danglu-knative-dev-290519",
    "generation": "1610564600595212",
    "metageneration": "1",
    "contentType": "application/octet-stream",
    "timeCreated": "2021-01-13T19:03:20.603Z",
    "updated": "2021-01-13T19:03:20.603Z",
    "storageClass": "STANDARD",
    "timeStorageClassUpdated": "2021-01-13T19:03:20.603Z",
    "size": "1682",
    "md5Hash": "DqB0N1pmMRX4mjv1llfoWQ==",
    "mediaLink": "https://www.googleapis.com/download/storage/v1/b/events-quickstart-danglu-knative-dev-290519/o/go-test-123.txt?generation=1610564600595212&alt=media",
    "contentLanguage": "en",
    "crc32c": "mA33eA==",
    "etag": "CIyGoNfMme4CEAE="
  }
```

### Code

go.mod

```
module xxxxx

go 1.13

require (
	github.com/cloudevents/sdk-go/v2 v2.3.1
	github.com/googleapis/google-cloudevents-go v0.0.0-20210109004349-be1f906e2061 // indirect
)
```

main.go

```go
import (
	"context"
	"fmt"
	"log"

	cloudevents "github.com/cloudevents/sdk-go/v2"
	"github.com/googleapis/google-cloudevents-go/cloud/storage/v1"
)

func Receive(event cloudevents.Event) {
        fmt.Printf("%+v\n", event)
	e, err := storage.UnmarshalStorageObjectData(event.Data())
	if err != nil {
		panic(err)
	}
	fmt.Printf("%+v\n", e)
	fmt.Printf("Detected change in GCS bucket: %s\n", event.Subject())
}

func main() {
	c, err := cloudevents.NewDefaultClient()
	if err != nil {
		log.Fatalf("failed to create client, %v", err)
	}
	log.Fatal(c.StartReceiver(context.Background(), Receive))
}

```

**Comment by eclipselu** [comment]
cc @bryeung

**Comment by grant** [comment]
Thanks for reporting.

Looks like the representation in JSON is a string but the library is expecting int64.

I think if we change the struct to:

```go
Generation              *int64              `json:"generation,omitempty"`
v--v
Generation              *int64              `json:"generation,string,omitempty"`
```

We shouldn't get the unmarshalling error.

https://github.com/googleapis/google-cloudevents-go/blob/master/cloud/storage/v1/storage_object_data.go#L31

If you're able to test that the above patch to the structs make things work, lmk.

---

A temporary workaround may be to install a previous version that didn't use int64:

```
github.com/googleapis/google-cloudevents-go@d0aaf89398e1cc04831c820e7e8e81c33198ac62
```

**Comment by eclipselu** [comment]
Thanks @grant, I just tested, I'm able to parse the body with 

```
github.com/googleapis/google-cloudevents-go@d0aaf89398e1cc04831c820e7e8e81c33198ac62
```

**Comment by eclipselu** [comment]
> I think if we change the struct to:
> 
> ```go
> Generation              *int64              `json:"generation,omitempty"`
> v--v
> Generation              *int64              `json:"generation,string,omitempty"`
> ```
> 
> We shouldn't get the unmarshalling error.

If we do this, integers in string representation (`"123"`) will work but integer representation will not (`123`) , see, https://play.golang.org/p/K9Fvz1hGE-H

**Comment by eclipselu** [comment]
I'm thinking if this might be an upstream issue that the event should conform to what https://github.com/googleapis/google-cloudevents/blob/master/proto/google/events/cloud/storage/v1/data.proto#L134 has defined. so the generation should be `"generation": 1610564600595212`

**Comment by grant** [comment]
> > I think if we change the struct to:
> > ```go
> > Generation              *int64              `json:"generation,omitempty"`
> > v--v
> > Generation              *int64              `json:"generation,string,omitempty"`
> > ```
> > 
> > 
> > We shouldn't get the unmarshalling error.
> 
> If we do this, integers in string representation (`"123"`) will work but integer representation will not (`123`) , see, https://play.golang.org/p/OJIjS4ZSf9u

The JSON serialized value will **always** be a string I believe, so this will not be a problem.

JSON only supports 32 bit integers, so serializing will always produce a string, iiuc.

**Comment by eclipselu** [comment]
> JSON only supports 32 bit integers, so serializing will always produce a string, iiuc.
> 
> This is a weird quirk with using JSON for our events.

TIL, Thanks, you're right! JSON cannot support int64, and neither for Javascript. It seems that we convert proto3 to jsonschema: https://github.com/googleapis/google-cloudevents/tree/master/tools/proto2jsonschema

Given that JSON is not on parity with proto3 in terms of int64, should we use string instead? is it a concern for the nodejs sdk as well as javascript does not support int64?

**Comment by eclipselu** [comment]
> Given that JSON is not on parity with proto3 in terms of int64, should we use string instead? is it a concern for the nodejs sdk as well as javascript does not support int64?

nvm, thanks for filing the issue in json-schema!

**Comment by grant** [comment]
> > I think if we change the struct to:
> > ```go
> > Generation              *int64              `json:"generation,omitempty"`
> > v--v
> > Generation              *int64              `json:"generation,string,omitempty"`
> > ```
> > 
> > 
> > We shouldn't get the unmarshalling error.
> 
> If we do this, integers in string representation (`"123"`) will work but integer representation will not (`123`) , see, https://play.golang.org/p/OJIjS4ZSf9u

I believe we explicitly don't need to accept integer representations (`123`), as the CloudEvent will **never** represent this value as a JSON Number. It will **always** be a _string_ per JSON serialization mapping [1].

[1] https://developers.google.com/protocol-buffers/docs/proto3#json

---

As such, I believe the solution is to simply annotate the 64 types correctly, such that there is no unmarshalling error for these strings:

- Golang types: `int64`, `uint64`, `float64`
  - Should have JSON annotation: `string`

## Local Test

```
go mod init hello
# ...add code
go run .
```

```go
package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	fmt.Println("Test:")

	var d MyType
	s := `{ "port": "1234123341234"}`
	err := json.Unmarshal([]byte(s), &d)

	if err == nil {
		fmt.Print(*d.Port)
	}
}

// MyType: test
type MyType struct {
	Port *int64 `json:"port,string,omitempty"`
}
```

**Comment by grant** [comment]
I've created a PR that should fix this issue.

**Comment by grant** [comment]
Hi @eclipselu, the latest version of this library (462a95ee482574e4632a82b32bd2056b9660aba2) should have a fix for unmarshalling the storage payload.

If you're still seeing the error, please provide exact repro steps like I have shown in https://github.com/googleapis/google-cloudevents-go/issues/39#issuecomment-782473649.
