### ISSUE TITLE
remove v1 suffixes on import paths

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-cloudevents-go#43]
## Expected Behavior

A v0/v1 module that contains no import paths with version numbers.

## Actual Behavior

Imports like: "github.com/googleapis/google-cloudevents-go/cloud/audit/v1"

## Details

Directories named `vX` have a meaning with Go and its module ecosystem. For v0/v1 no suffix should be added. It is for this reason that when we generate GAPICs we do so with apiv1/api2beta.

**Comment by grant** [comment]
Given our Eventarc CloudEvent type versions mean something different than normal API versions, it's rather infeasible to remove this or change this. We have this versioning throughout the product and libraries.

**Comment by tbpg** [comment]
> We have this versioning throughout the product and libraries.

We add an "api" prefix to avoid this in libraries. There are a couple that snuck through, but in general this isn't a problem for libraries.
