### ISSUE TITLE
Remove multiple small packages

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-cloudevents-go#44]
## Expected Behavior

A single package that contains all cloud event types

## Actual Behavior

Directories like cloud/audit, cloud/cloudbuild, cloud/firestore, etc

## Details

Maybe all of the events could be in the same package and just different files?

**Comment by grant** [comment]
Given we want each event type to have its own scope, I don't think we can combine all packages into one larger package.

> https://blog.golang.org/package-names
> "Within a package, code can refer to any identifier (name) defined within"

If we combine packages, there would be duplicate identifiers (that aren't necessarily the same type).

---

Current:

```
pubsub.MessagePublishedData
```

Potential change:

```
googlecloudevents.MessagePublishedData
```

---

We'd have conflicts with multiple event types in the same file, and a change would be less readable, so I'm not sure how we'd concretely change this. As such, closing this issue.
