### ISSUE TITLE
Consider helpers or different types for pointers to builtins

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-cloudevents-go#47]
## Expected Behavior

```go
// Idea #1
type Foo struct {
   Bar *string 
}

func main() {
   foo := Foo{
      // a helper that returns a pointer
      Bar: cloudevent.String("test"),
   }
}
```

```go
// Idea #2
type Foo struct {
   Bar optional.String 
}

func main() {
   foo := Foo{
      Bar: "test",
   }
}
```

## Actual Behavior

```go
type Foo struct {
	Bar *string
}

func main() {
	bar := "test"
	foo := Foo{
                 // Variable needs to be predeclared and a reference taken from it.
		Bar: &bar,
	}
}

```

## Details

I like the choice to make the structs have pointer fields in general, not doing so in the Go apiary libraries has led to much confusion. But at the same time they can be hard to work with. For this reason in the GAPIC libraries we have the [optional](https://pkg.go.dev/cloud.google.com/go/internal/optional) package that is [referenced in structs directly](https://pkg.go.dev/cloud.google.com/go/pubsub#RetryPolicy). Another pattern I have seen is to provide some helper functions to convert to and from pointers. Have you gathered any user feedback in this area?

**Comment by grant** [comment]
Sync'd in Google Docs, we don't create events and so we don't need this functionality.
