### ISSUE TITLE
Remove marshaller/unmarshaller functions

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-cloudevents-go#48]
## Expected Behavior

Users of this library should work with the [json](https://pkg.go.dev/encoding/json) package directly.

## Actual Behavior

There are non-standard custom marshaller functions/methods. [ex1](https://pkg.go.dev/github.com/googleapis/google-cloudevents-go/cloud/audit/v1#UnmarshalLogEntryData) [ex2](https://pkg.go.dev/github.com/googleapis/google-cloudevents-go/cloud/audit/v1#LogEntryData.MarshalLogEntryData)

## Details

I don’t think there is a need from the customer marshallers/unmarshallers. If anything special is needed that is not directly supported by the json package I would instead [implement a custom JSON marshaller](https://pkg.go.dev/encoding/json#example-package-CustomMarshalJSON) that is respected by the json package.

**Comment by grant** [comment]
Yup, we can remove this in the post-generator.
