### ISSUE TITLE
label deprecated fields conventionally 

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-cloudevents-go#50]
## Expected Behavior

```go
// Foo does something.
// Deprecated: use Bar instead.
type Foo struct {}
```

## Actual Behavior

```go
// Deprecated, use bar instead.
type Foo struct {}
```

## Details

For [deprecated fields](https://pkg.go.dev/github.com/googleapis/google-cloudevents-go/cloud/audit/v1#ServiceData) it would be nice to match [godoc conventions](https://github.com/golang/go/wiki/Deprecated) so users can get a warning in their editor.

**Comment by grant** [comment]
I see the only reference to deprecated in 2 places in this file:

https://github.com/googleapis/google-cloudevents-go/blob/462a95ee482574e4632a82b32bd2056b9660aba2/cloud/audit/v1/log_entry_data.go

**Comment by grant** [comment]
Sent upstream proto change CL.

**Comment by grant** [comment]
Waiting on https://github.com/googleapis/google-cloudevents/pull/192 before I can regenerate and close.
