### ISSUE TITLE
Cannot unmarshall logEntry.Severity

### ISSUE THREAD

**Issue by salrashid123** [googleapis/google-cloudevents-go#68]
I'm trying unmarshall  and inbound cloudEvent Audit entriy into `github.com/googleapis/google-cloudevents-go/cloud/audit/v1`.`LogEntryData`  as shown below.

However, the `Severity` field that is sent is just a string while the [auditv1](https://github.com/googleapis/google-cloudevents-go/blob/master/cloud/audit/v1/log_entry_data.go#L368) below defines it 

```golang
type Severity struct {
	Enum    *InsertID
	Integer *int64
}
```

while google eventarc send over just a string value

```json
 "{"protoPayload":{"status":{},"authenticationInfo....

 "severity":"NOTICE",              <<<<<<<<<<<<<
```

which leads to the exception

```
 json: cannot unmarshal string into Go struct field LogEntryData.severity of type audit.Severity 
```

---

```golang
import (

	cloudevents "github.com/cloudevents/sdk-go/v2"
	auditv1 "github.com/googleapis/google-cloudevents-go/cloud/audit/v1"
)

func Receive(ctx context.Context, event cloudevents.Event) error {
	fmt.Printf("  EventID: %s\n", event.ID())
	fmt.Printf("  EventType: %s \n", event.Type())
	fmt.Printf("  Event Context: %+v\n", event.Context)
	fmt.Printf("  Protocol Context: %+v\n", pscontext.ProtocolContextFrom(ctx))
	switch event.Type() {
	case auditLogEventType:
		auditData := &auditv1.LogEntryData{}
		if err := event.DataAs(auditData); err != nil {
			fmt.Printf("DataAs Error %v", err)
			return fmt.Errorf("Got Data Error: %s\n", err)
		}
		fmt.Printf("Audit auditLogEventType ResourceName %s\n", *auditData.ProtoPayload.ResourceName)

	default:
	}
	return nil
}
func main() {
	c, err := cloudevents.NewDefaultClient()
	err = c.StartReceiver(context.Background(), Receive)
}

```

---

see also https://github.com/googleapis/google-cloudevents-go/issues/22

**Comment by grant** [comment]
Thanks for the bug report.

It looks like we need to have the type `Severity` to be a `string` (or maybe a `interface{}`). I believe this is what Eventarc converts enum types to. We can do this by changing the type, either at the JSON schema level or just at the Go generator level.

Current:

- Go (struct with enum and int): https://github.com/googleapis/google-cloudevents-go/blob/master/cloud/audit/v1/log_entry_data.go#L368
- JSON Schema (oneof int / string): https://github.com/googleapis/google-cloudevents/blob/1a53629cf9007b98c6e9812695b31c693f782061/jsonschema/google/events/cloud/audit/v1/LogEntryData.json#L528
- Proto (enum): https://github.com/googleapis/google-cloudevents/blob/master/proto/google/events/cloud/audit/v1/data.proto#L61

**Comment by grant** [comment]
I think the solution is to do the following:

- Convert all JSON schema "oneOf string | int" to "type string". There are 12 cases of this when I searched. In reality, the data sent in JSON is in the form of a string, so clients should be able to parse the field as a string.

**Comment by grant** [comment]
I've created a PR and test for solving this issue. I'll try to get that through.
Feel free to try out the branch and LMK if unmarshalling works for you.

**Comment by salrashid123** [comment]
thanks, seem to work fine


```
module main

go 1.15

require (
	github.com/cloudevents/sdk-go/protocol/pubsub/v2 v2.4.1 // indirect
	github.com/googleapis/google-cloudevents v1.3.2-0.20210630234950-b308e1ce6512 // indirect
	github.com/googleapis/google-cloudevents-go v0.1.1-0.20210630234412-c5987988a6b2 // indirect

)

```
```golang
		//	auditv1 "github.com/googleapis/google-cloudevents-go/cloud/audit/v1"
		auditData := &auditv1.LogEntryData{}
		if err := event.DataAs(auditData); err != nil {
			fmt.Printf("DataAs Error %v", err)
			return fmt.Errorf("Got Data Error: %s\n", err)
		}
		log.Printf("Audit  %s\n", *auditData.Severity)
```
